### 1. Not in Function Form

In [108]:
import numpy as np
board = [[0 for x in range(4)] for y in range(4)]

def checker(board, row_idx, cols, pos):
    if row_idx == 0:
        return True
    x_prev, y_prev = row_idx-1, board[row_idx-1].index(1)
    
    if (pos in cols) or (pos == y_prev) or (pos == y_prev + 1) or (pos == y_prev - 1):
        return False
    return True

def backtrack(board, row_idx, cols):
    print("back tracked!")
    row_idx -= 1
    last_pos = cols.pop()
    board[row_idx][last_pos] = 0
    if last_pos == 3:
        board, row_idx, cols, last_pos = backtrack(board, row_idx, cols)
    return board, row_idx, cols, last_pos


row_idx = 0
cols = []
back_tracked = False
last_pos = 0
while row_idx < 4:
    row = board[row_idx]
    print(f"Row: {row_idx+1}")
    print(f"last_pos: {last_pos}")

    for pos in range(last_pos+1 if back_tracked else 0, 4):
        back_tracked = False
        if checker(board, row_idx, cols, pos):
            row[pos] = 1
            cols.append(pos)
            row_idx += 1
            print(np.array(board))
            print("=================")
            break
        if (pos == 3):
            board, row_idx, cols, last_pos = backtrack(board, row_idx, cols)
            back_tracked = True


Row: 1
last_pos: 0
[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Row: 2
last_pos: 0
[[1 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]]
Row: 3
last_pos: 0
back tracked!
Row: 2
last_pos: 2
[[1 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]
Row: 3
last_pos: 2
[[1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 0 0 0]]
Row: 4
last_pos: 2
back tracked!
Row: 3
last_pos: 1
back tracked!
back tracked!
Row: 1
last_pos: 0
[[0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Row: 2
last_pos: 0
[[0 1 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]
Row: 3
last_pos: 0
[[0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 0 0]]
Row: 4
last_pos: 0
[[0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]]


### 2. Function Form

In [131]:
import numpy as np

def checker(board, row_idx, cols, pos):
    if row_idx == 0:
        return True
    x_prev, y_prev = row_idx-1, board[row_idx-1].index(1)
    
    if (pos in cols) or (pos == y_prev) or (pos == y_prev + 1) or (pos == y_prev - 1):
        return False
    return True

def backtrack(board, row_idx, cols, N):
    # print("back tracked!")
    row_idx -= 1
    last_pos = cols.pop()
    board[row_idx][last_pos] = 0
    if last_pos == N-1:
        board, row_idx, cols, last_pos = backtrack(board, row_idx, cols, N)
    return board, row_idx, cols, last_pos


def NQueen(N):
    board = [[0 for x in range(N)] for y in range(N)]
    row_idx = 0
    cols = []
    back_tracked = False
    last_pos = 0
    
    while row_idx < N:
        row = board[row_idx]
        # print(f"Row: {row_idx+1}")
        # print(f"last_pos: {last_pos}")

        for pos in range(last_pos+1 if back_tracked else 0, N):
            back_tracked = False
            if checker(board, row_idx, cols, pos):
                row[pos] = 1
                cols.append(pos)
                row_idx += 1
                # print(np.array(board))
                # print("=================")
                break
            if (pos == N-1):
                board, row_idx, cols, last_pos = backtrack(board, row_idx, cols, N)
                back_tracked = True
    return board


In [133]:
np.array(NQueen(4))

array([[0, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 0]])

### 3. Multiple Solutions

In [159]:
import numpy as np

def checker(board, row_idx, cols, pos):
    if row_idx == 0:
        return True
    x_prev, y_prev = row_idx-1, board[row_idx-1].index(1)
    
    if (pos in cols) or (pos == y_prev) or (pos == y_prev + 1) or (pos == y_prev - 1):
        return False
    return True

def backtrack(board, row_idx, cols, N):
    # print("back tracked!")
    row_idx -= 1
    last_pos = cols.pop()
    board[row_idx][last_pos] = 0
    if last_pos == N-1:
        board, row_idx, cols, last_pos = backtrack(board, row_idx, cols, N)
    return board, row_idx, cols, last_pos


def NQueen(N):
    all_solutions= {}

    start = 0
    while start < N-1:
        
        board = [[0 for x in range(N)] for y in range(N)]
        row_idx = 0
        cols = []
        back_tracked = False
        last_pos = 0

        while row_idx < N:
            row = board[row_idx]
            # print(f"Row: {row_idx+1}")
            # print(f"last_pos: {last_pos}")

            for pos in range(last_pos+1 if back_tracked else start, N):
                start = 0
                back_tracked = False
                if checker(board, row_idx, cols, pos):
                    row[pos] = 1
                    cols.append(pos)
                    row_idx += 1
                    # print(np.array(board))
                    # print("=================")
                    break
                if (pos == N-1):
                    board, row_idx, cols, last_pos = backtrack(board, row_idx, cols, N)
                    back_tracked = True
    
        start = board[0].index(1)+1
        all_solutions["sln" + str(start)] = board

        
    for soln in all_solutions.values():
        index_solution = []
        for x in range(len(soln)):
            for y in range(len(soln[x])):
                if soln[x][y] == 1:
                    index_solution.append([x, y])
        print(index_solution)

    return all_solutions


In [161]:
NQueen(6)

[[0, 0], [1, 2], [2, 4], [3, 1], [4, 3], [5, 5]]
[[0, 1], [1, 3], [2, 0], [3, 4], [4, 2], [5, 5]]
[[0, 2], [1, 0], [2, 3], [3, 5], [4, 1], [5, 4]]
[[0, 3], [1, 0], [2, 2], [3, 4], [4, 1], [5, 5]]
[[0, 4], [1, 0], [2, 2], [3, 5], [4, 1], [5, 3]]


{'sln1': [[1, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 1, 0],
  [0, 1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0],
  [0, 0, 0, 0, 0, 1]],
 'sln2': [[0, 1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0],
  [1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 0],
  [0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 1]],
 'sln3': [[0, 0, 1, 0, 0, 0],
  [1, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0],
  [0, 0, 0, 0, 0, 1],
  [0, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 0]],
 'sln4': [[0, 0, 0, 1, 0, 0],
  [1, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 1, 0],
  [0, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 1]],
 'sln5': [[0, 0, 0, 0, 1, 0],
  [1, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 1],
  [0, 1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0]]}

### Final version

In [194]:
def checker(board, row_idx, cols, pos):
    """
    checks if a queen could be placed at
    a specific position in a row
    """
    
    # Could be placed anywhere on the first row
    if row_idx == 0:
        return True
    # Coordinates of previous placements
    crds = [(x, cols[x]) for x in range(len(cols))]

    # Can't put on cols that already have queens
    if (pos in cols):
        return False
    # Check if the pos lies at a diagonal to other queens
    not_equal = [abs(ele[0]-row_idx) != abs(ele[1] - pos)  for ele in crds]
    if not all(not_equal):
        return False

    return True

def backtrack(board, row_idx, cols, N):
    """
    Go to the previous row and relocate the Queen
    """

    row_idx -= 1
    last_pos = cols.pop()
    board[row_idx][last_pos] = 0
    if last_pos == N-1:
        board, row_idx, cols, last_pos = backtrack(board, row_idx, cols, N)
    return board, row_idx, cols, last_pos


def NQueen(N):
    """
    prints all the possible cooridnates of the N queens
    in the NxN chess board
    """

    # Dict to save all the solutions in list of lists
    all_solutions= {}
    # Initialize the first column to place the queen at each row
    start = 0
    # Loop until all solutions are found
    while start < N:
        
        board = [[0 for x in range(N)] for y in range(N)]
        row_idx = 0
        cols = []
        back_tracked = False
        last_pos = 0

        while row_idx < N:
            row = board[row_idx]

            for pos in range(last_pos+1 if back_tracked else start, N):
                start = 0
                back_tracked = False
                
                if checker(board, row_idx, cols, pos):
                    row[pos] = 1
                    cols.append(pos)
                    row_idx += 1
                    break

                if (pos == N-1):
                    board, row_idx, cols, last_pos = backtrack(board, row_idx, cols, N)
                    back_tracked = True
    
        start = board[0].index(1)+1
        all_solutions["sln" + str(start)] = board

    # Extract the positions of the the queens 
    for soln in all_solutions.values():
        index_solution = []
        for x in range(len(soln)):
            for y in range(len(soln[x])):
                if soln[x][y] == 1:
                    index_solution.append([x, y])
        print(index_solution)
    return all_solutions


In [195]:
NQueen(5)

[[0, 0], [1, 2], [2, 4], [3, 1], [4, 3]]
[[0, 1], [1, 3], [2, 0], [3, 2], [4, 4]]
[[0, 2], [1, 0], [2, 3], [3, 1], [4, 4]]
[[0, 3], [1, 0], [2, 2], [3, 4], [4, 1]]
[[0, 4], [1, 1], [2, 3], [3, 0], [4, 2]]


{'sln1': [[1, 0, 0, 0, 0],
  [0, 0, 1, 0, 0],
  [0, 0, 0, 0, 1],
  [0, 1, 0, 0, 0],
  [0, 0, 0, 1, 0]],
 'sln2': [[0, 1, 0, 0, 0],
  [0, 0, 0, 1, 0],
  [1, 0, 0, 0, 0],
  [0, 0, 1, 0, 0],
  [0, 0, 0, 0, 1]],
 'sln3': [[0, 0, 1, 0, 0],
  [1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0],
  [0, 1, 0, 0, 0],
  [0, 0, 0, 0, 1]],
 'sln4': [[0, 0, 0, 1, 0],
  [1, 0, 0, 0, 0],
  [0, 0, 1, 0, 0],
  [0, 0, 0, 0, 1],
  [0, 1, 0, 0, 0]],
 'sln5': [[0, 0, 0, 0, 1],
  [0, 1, 0, 0, 0],
  [0, 0, 0, 1, 0],
  [1, 0, 0, 0, 0],
  [0, 0, 1, 0, 0]]}